vich_uploader:
    db_driver: orm

    mappings:
        evenement_images:
            uri_prefix: '%evenement_images%'
            upload_destination: '%kernel.project_dir%/public/%evenement_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
